name: Test and build
on: [push]

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('yarn.lock') }}

      - name: Install Modules
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

      - name: Prettier
        run: yarn run format
        
      - name: Build
        run: yarn run build
